server:
  port: 8080
  servlet:
    session:
      timeout: 1200
  #  maxHttpHeaderSize:102400000
  #  maxHttpPostSize :102400000
  max-http-header-size: 102400000
  tomcat:
    max-http-post-size: 102400000

spring:
  datasource:
    url: jdbc:mysql://47.94.130.23:3306/nideshop?autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&URIEncoding="UTF-8"
    username: root
    password: Oo0chenyujinOo0
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


