#serve 配置端口和session过期时间（单位秒）
server:
  port: 8080
  servlet:
    session:
      timeout: 1200
  #  maxHttpHeaderSize:102400000   #设定HttpHeader请求头大小
  #  maxHttpPostSize :102400000
  max-http-header-size: 102400000
  tomcat:
    max-http-post-size: 102400000
#database oracle 数据库连接，数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.94.130.23:3306/nideshop?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&URIEncoding="UTF-8"
    username: root
    password: Oo0chenyujinOo0@
    driver-class-name: com.mysql.jdbc.Driver

#坑点0 配置mybatis的xml位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true


